### ISSUE TITLE
Classes not being merged properly

### ISSUE THREAD

**Issue by antonsamper** [ben-eb/postcss-merge-rules#12] opened 2015-12-21 10:40 UTC
When duplicate properties are repeated in multiple classes, not all the classes are merged. I think this may have something to do with the cache.

For example if you parse the following CSS (generated by spritesmith):
```
.test1 {
  background-image: url(../../images/testimage.png);
  background-position: 0px 0px;
  width: 67px;
  height: 26px;
}
.test2 {
  background-image: url(../../images/testimage.png);
  background-position: -189px 0px;
  width: 67px;
  height: 21px;
}
.test3 {
  background-image: url(../../images/testimage.png);
  background-position: -129px -48px;
  width: 67px;
  height: 18px;
}
.test4 {
  background-image: url(../../images/testimage.png);
  background-position: -379px -18px;
  width: 28px;
  height: 14px;
}
.test5 {
  background-image: url(../../images/testimage.png);
  background-position: 0px -48px;
  width: 46px;
  height: 25px;
}
.test6 {
  background-image: url(../../images/testimage.png);
  background-position: -263px -36px;
  width: 34px;
  height: 14px;
}

```

The output is this:
```
.test1, .test2 {
  background-image: url(../../images/testimage.png);
  width: 67px
}

.test2 {
  background-position: -189px 0;
  height: 21px
}

.test3 {
  background-position: -129px -48px;
  width: 67px;
  height: 18px
}

.test3, .test4 {
  background-image: url(../../images/testimage.png)
}

.test4 {
  background-position: -379px -18px;
  width: 28px;
  height: 14px
}

.test5 {
  background-position: 0 -48px;
  width: 46px;
  height: 25px
}

.test5, .test6 {
  background-image: url(../../images/testimage.png)
}

.test6 {
  background-position: -263px -36px;
  width: 34px;
  height: 14px
}
```

**Comment by ben-eb** [comment] 2015-12-21 10:53
Duplicate of https://github.com/ben-eb/postcss-merge-rules/issues/7

**Closed by ben-eb** 2015-12-21 10:53 UTC
Labels: duplicate
