### ISSUE TITLE
Property order

### ISSUE THREAD

**Issue by dhoko** [ben-eb/postcss-merge-rules#13] opened 2015-12-29 08:17 UTC
Hi, 

[from our discussion on twitter](https://twitter.com/ben_eb/status/681582388917452801)

### Expected behaviour
Test:

```
{
  message: 'should respect property order and do nothing',
  fixture: 'body { overflow: hidden; overflow-y: scroll; overflow-x: hidden;} main { overflow: hidden }',
  expected: 'body { overflow: hidden; overflow-y: scroll; overflow-x: hidden;} main { overflow: hidden }'
}
```

### Actual behaviour

>  Failed Tests: There was 1 failure

```css
body { 
  overflow-y: scroll; 
  overflow-x: hidden;
} 
body,main { overflow: hidden;}
```

I don't think this is really an issue.

**Comment by ben-eb** [comment] 2015-12-29 09:28
It might be a fault in the logic that caused [this issue](https://github.com/ben-eb/cssnano/issues/87) also; the module shouldn't merge rules together where it would cause breakage like this. For example:

```
message: 'should not incorrectly extract margin properties',
fixture: 'h2{margin-bottom:20px}h1{margin:10px;margin-bottom:20px}',
expected: 'h2{margin-bottom:20px}h1{margin:10px;margin-bottom:20px}'
```

Will have a look when I can.

**Comment by hzlzh** [comment] 2016-01-07 03:19
Same here:

In 
```css
.mod-111 {
    display: inline-block;
    width: 0;
    height: 0;
    border-width: 8px;
    border-style: dashed;
    border-color: transparent;
    border-top-width: 0;
    border-bottom-color: #111111;
    border-bottom-style: solid;
    top: 4px;
}

.mod-111 {
    display: inline-block;
    width: 0;
    height: 0;
    border-width: 8px;
    border-style: dashed;
    border-color: transparent;
    border-top-width: 0;
    border-bottom-color: #222222;
    border-bottom-style: solid;
    top: 5px;
}
```
Out
```css

.mod-111{border-bottom-color:#111111;top:4px}
.mod-111,.mod-222{display:inline-block;width:0;height:0;border:8px dashed transparent;border-top-width:0;border-bottom-style:solid}
.mod-111{border-bottom-color:#222222;top:5px}
```

**Comment by elektronik2k5** [comment] 2016-03-03 09:00
Seems like a duplicate of https://github.com/ben-eb/postcss-merge-rules/issues/14

**Closed** 2016-04-17 12:11 UTC
Labels: bug
